trigger:
- main  # or the branch you want to trigger from
 
pool: 
  name: Test1
  # vmImage: 'ubuntu-latest'  # Select an Ubuntu VM for running tests
 
jobs:
- job: RunSeleniumTests
  displayName: 'Run Selenium Tests'
  steps:
 
    # Step 1: Install Python
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
        addToPath: true

    # Step 2: Install dependencies
    - script: |
        python -m pip install --upgrade pip
        pip install -r project/requirements.txt
      displayName: 'Install dependencies'
 
    # Step 3: Set up WebDriver (Chromium)
    - script: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
      displayName: 'Install Chromium Browser'
 
    # Step 4: Set the environment variable for headless browser testing
    # - script: |
    #     export DISPLAY=:99
    #   displayName: 'Set DISPLAY environment variable for headless testing'
 
    # Step 3: Run Selenium Tests using pytest
    - script: |
        pytest --html=project/reports/report.html
      displayName: 'Run UI Selenium Tests'

    # Step 4: Download Test Artifacts
    # - task: DownloadPipelineArtifact@1
    #   inputs:
    #     buildType: 'current'
    #     : 'single'
    #     artifactName: 'my-artifact'
    #     downloadPath: '$(Build.ArtifactStagingDirectory)'
 
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: Project/reports
        artifactName: 'Automation_test_results'
        publishLocation: 'Container'
