trigger:
- main  # or the branch you want to trigger from
 
pool:
  name: Test1
  # vmImage: 'ubuntu-latest'  # Select an Ubuntu VM for running tests
 
jobs:
- job: RunSeleniumTests
  displayName: 'Run Selenium Tests'
  steps:
 
    # Step 1: Install Python
    - script: |
        echo "##vso[task.setvariable variable=LD_LIBRARY_PATH;]:/home/chandap10/myagent/az_work/_tool/Python/3.11.11/x64/lib"
      displayName: Add the Python library path to the Linux native code library path
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
        addToPath: true
 
    # - checkout: self

    # Step 2: Install dependencies
    - script: |
        python -m pip install --upgrade pip
        pip install -r Project/requirements.txt
      displayName: 'Install dependencies'
 
    # Step 3: Set up WebDriver (Chromium)
    - script: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
      displayName: 'Install Chromium Browser'
 
    # Step 4: Set the environment variable for headless browser testing
    - script: |
        export DISPLAY=:99
      displayName: 'Set DISPLAY environment variable for headless testing'
 
    # Step 5: Run Selenium Tests using pytest
    - script: |
        pytest --html=./reports/report.html
      displayName: 'Run UI Selenium Tests'

    # Step 6: Download Test Artifacts
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: reports
 
    # Step 6: Upload Test Results (Optional: If you want to visualize test results in Azure DevOps)
    # - task: PublishTestResults@2
    #   inputs:
    #     testResultsFormat: 'JUnit'
    #     testResultsFiles: '**/test-*.xml'
    #     failTaskOnFailedTests: true